name: CI

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    name: Continuous Integration
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.12"
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.1.2"
      - name: "Install python dependencies"
        run: "pip install -r requirements.txt"
      - name: "Download RDA files and validate them"
        run: "make rda/validate"
      - name: "Convert to CSV and package the data"
        run: "make csv/csv.zip"
      - name: "Release data for tags"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "csv/csv.zip"
